# Generated by Django 4.2 on 2023-04-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='title',
        ),
    ]
